apiVersion: openslo/v1
kind: SLO
metadata:
  name: foo-slo
  displayName: Foo SLO # make variable
spec:
  service: service_name # make variable
  indicator:
    metadata:
      name: lambda-error
      displayName: Lambda Error # make variable
    spec:
      thresholdMetric:
        metricSource:
          type: CloudWatch
          spec:
            rawMetric:
              query:
                cloudwatch:
                  region: eu-central-1 # make variable
                  namespace: AWS/Lambda # make variable
                  metricName: Errors # make variable
                  stat: Sum # make Variable
                  dimensions:
                    - name: FunctionName
                      value: LambdaName # make variable
  objectives:
    - displayName: Errors # make variable
      op: gte # make variable
      value: 100 # make variable
      target: 0.99 # make variable
  timeWindow:
    - duration: 28d # make variable
      isRolling: true # make variable
  budgetingMethod: Occurrences # make variable
